export const FETCH_AUTHORIZATION = 'FETCH_AUTHORIZATION';
export const FETCH_AUTHORIZATION_LOADING = 'FETCH_AUTHORIZATION_LOADING';
export const FETCH_AUTHORIZATION_SUCCESS = 'FETCH_AUTHORIZATION_SUCCESS';
export const FETCH_AUTHORIZATION_FAILURE = 'FETCH_AUTHORIZATION_FAILURE';
export const RESET_ACTIVE_AUTHORIZATION = 'RESET_ACTIVE_AUTHORIZATION';